nelmio_api_doc:
  documentation:
    info:
      title: MAI Survey Service
      description: MAI Survey Service
      version: 1.0.0
    tags:
      - name: health
        description: Ручки для проверки работоспособности сервера
      - name: auth
        description: Ручки для авторизации и аутентификации
      - name: user-data
        description: Ручки для работы с данными пользователей
      - name: groups
        description: Ручки для работы с группами
      - name: me
        description: Ручки для работы с "собой"
      - name: users
        description: Ручки для работы с пользователями
      - name: subjects
        description: Ручки для работы с предметами
      - name: user-subjects
        description: Ручки для работы с предметами, привязанными к пользователям
      - name: roles
        description: Ручки для получения ролей
    servers:
      - url: https://mai-survey.net
      - url: http://mai-survey.loc
        description: Local development server
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: [ ]
  areas: # to filter documented areas
    path_patterns:
      - ^(?!(/doc|/_.*)$) # Accepts routes under /api except /api/doc and /_* (development debug routes)
