# config/packages/rate_limiter.yaml
framework:
  rate_limiter:
    api:
      policy: 'sliding_window'
      limit: 30
      interval: '10 seconds'
      cache_pool: 'cache.rate_limiter'
      lock_factory: 'lock.default.factory'